Repository GDG-on-Campus-KNU/4th-1st-Project-Pium-BE, pull requests merged in 2025-05, with the labels that each got.

#16 Feat: 건물 검색기능 추가
  src/main/java/gdg/pium/domain/department/Department.java
  src/main/java/gdg/pium/domain/lecture/Lecture.java
  src/main/java/gdg/pium/domain/place/controller/PlaceController.java
  src/main/java/gdg/pium/domain/place/dto/response/PlaceSearchResponse.java
  src/main/java/gdg/pium/domain/place/entity/Place.java
  src/main/java/gdg/pium/domain/place/repository/PlaceRepository.java
  src/main/java/gdg/pium/domain/place/service/PlaceService.java
  src/main/java/gdg/pium/domain/placedepartment/entity/PlaceDepartment.java
  src/main/java/gdg/pium/domain/placedepartment/repository/PlaceDepartmentRepository.java
Labels: feat

#19 Refactor/#12
  src/main/java/gdg/pium/PiumApplication.java
  src/main/java/gdg/pium/domain/like/controller/LikeController.java
  src/main/java/gdg/pium/domain/like/entity/Like.java
  src/main/java/gdg/pium/domain/like/repository/LikeRepository.java
  src/main/java/gdg/pium/domain/like/service/LikeService.java
  src/main/java/gdg/pium/domain/post/controller/PostController.java
  src/main/java/gdg/pium/domain/post/dto/request/PostCreateRequest.java
  src/main/java/gdg/pium/domain/post/dto/response/PostInfoResponse.java
  src/main/java/gdg/pium/domain/post/entity/Post.java
  src/main/java/gdg/pium/domain/post/service/PostService.java
  src/main/java/gdg/pium/domain/user/entity/User.java
  src/main/java/gdg/pium/global/entity/BaseEntity.java
  src/main/java/gdg/pium/global/exception/ErrorCode.java
  src/main/java/gdg/pium/global/util/DateTimeUtil.java
Labels: refac

#21 🐛 Fix - 게시글 사용자 정보 잘못 불러지는 거 수정
  src/main/java/gdg/pium/domain/post/dto/response/PostInfoResponse.java
Labels: bug
